### ISSUE TITLE
Hidden core proxy planets are visible

### ISSUE THREAD

**Issue by xen-42** [GameWyrm/HearthsNeighbor#3]
If you travel out far enough you can see the proxies for the cores, which should be invisible. 

Maybe NH could add a feature to easily grab the proxies for you, else you can just do something like GameObject.FindObjectsOfType<NHProxy>() and then check if their planets match the cores then delete them since you should never see the distant planets

**Comment by GameWyrm** [comment]
Fixed in v1.0.2
