### ISSUE TITLE
Derelict ship is outside of suns sphere of influence

### ISSUE THREAD

**Issue by xen-42** [GameWyrm/HearthsNeighbor#4]
Because of this, if you park your ship in orbit next to it you slowly drift away because the ship is no longer attracted to the sun. You can fix this by applying "sphereOfInfluenceOverride" to the sun so that it at least reaches the derelicts orbit.

**Comment by GameWyrm** [comment]
Applying the Sphere Of Influence override fix makes the exploration music not play. Since this is a pretty minor bug, and you can easily deal with it by parking on the obvious landing pad, this will not be fixed for now.
