### ISSUE TITLE
Cores might be showing over the suns atmosphere

### ISSUE THREAD

**Issue by xen-42** [GameWyrm/HearthsNeighbor#6]
![image](https://github.com/GameWyrm/HearthsNeighbor/assets/22628069/3b6a6d54-2381-4b85-bed4-48e32c88f0ef)

You can see in the picture it doesn't actually block the suns surface and therefore is unlikely to be caused by a cloaking field bug. I'd just try recreating this.

**Comment by GameWyrm** [comment]
Issue with New Horizons, apparently fixed on its end now. 

Closing as not an issue with HN.
